name: Gold Price Tracker

on:
  schedule:
    # Cú pháp Cron: Chạy mỗi 30 phút
    - cron: '*/30 * * * *'
  workflow_dispatch: # Cho phép anh bấm nút chạy tay để test

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Cấp quyền cho bot được sửa file và push code

    steps:
      - name: Kéo mã nguồn về máy chủ
        uses: actions/checkout@v4

      - name: Cài đặt Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Cài đặt thư viện
        run: pip install -r requirements.txt

      - name: Chạy động cơ cào dữ liệu
        run: python scraper.py

      - name: Commit và Đẩy file CSV mới lên Repo
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add gold_market_log.csv
          # Lệnh || exit 0 để bot không báo lỗi nếu 30p qua giá không đổi
          git commit -m "Auto-update giá vàng" || exit 0 
          git push
